export const JOB_ADDED = 'JOB_ADDED';
export const JOB_SAVED_SUCCESSS = 'JOB_SAVED_SUCCESSS';
export const JOB_SAVED_FAILURE = 'JOB_SAVED_FAILURE';
export const SET_SEARCHED_JOBS = 'SET_SEARCHED_JOBS';

export const CONTACT_ADDED = 'CONTACT_ADDED';
export const SET_SEARCHED_CONTACTS = 'SET_SEARCHED_CONTACTS';

export const COMMUNITY_ADDED = 'COMMUNITY_ADDED';
export const COMMUNITY_SAVED_SUCCESSS = 'COMMUNITY_SAVED_SUCCESSS';
export const COMMUNITY_SAVED_FAILURE = 'COMMUNITY_SAVED_FAILURE';
export const SET_SEARCHED_COMMUNITIES = 'SET_SEARCHED_COMMUNITIES';

export const IMAGE_SAVED_STARTED = 'IMAGE_SAVED_STARTED';
export const IMAGE_SAVED_SUCCESS = 'IMAGE_SAVED_SUCCESS';
export const IMAGE_SAVED_FAILURE = 'IMAGE_SAVED_FAILURE';
